.TH "Carte" 3 "Wed Apr 26 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Carte
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <carte\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCarte\fP ()"
.br
.ti -1c
.RI "\fBCarte\fP (int taille, std::string name, std::string description)"
.br
.ti -1c
.RI "int \fBverif_taille\fP (int taille)"
.br
.ti -1c
.RI "void \fBcoordonneejoueur\fP ()"
.br
.ti -1c
.RI "void \fBcoordonneeobstacle\fP ()"
.br
.ti -1c
.RI "void \fBcoordonneemonstre\fP ()"
.br
.ti -1c
.RI "void \fBaffichage_normal\fP ()"
.br
.ti -1c
.RI "int \fBnbLigneFichier\fP (std::string nomFichier)"
.br
.ti -1c
.RI "void \fBsauvegarde\fP ()"
.br
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.ti -1c
.RI "std::string \fBgetDescription\fP ()"
.br
.ti -1c
.RI "void \fBsetName\fP (std::string name)"
.br
.ti -1c
.RI "void \fBsetDescription\fP (std::string desc)"
.br
.ti -1c
.RI "void \fBsetPlateau\fP (int taille)"
.br
.ti -1c
.RI "void \fBsetCase\fP (int i, int j, std::string value)"
.br
.ti -1c
.RI "\fBCarte\fP \fBoperator=\fP (const \fBCarte\fP &a_copier)"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Carte::Carte ()"

.SS "Carte::Carte (int taille, std::string name, std::string description)"

.SH "Member Function Documentation"
.PP 
.SS "void Carte::affichage_normal ()"

.SS "void Carte::coordonneejoueur ()"

.SS "void Carte::coordonneemonstre ()"

.SS "void Carte::coordonneeobstacle ()"

.SS "std::string Carte::getDescription ()"

.SS "std::string Carte::getName ()"

.SS "int Carte::nbLigneFichier (std::string nomFichier)"

.SS "\fBCarte\fP Carte::operator= (const \fBCarte\fP & a_copier)"

.SS "void Carte::sauvegarde ()"

.SS "void Carte::setCase (int i, int j, std::string value)"

.SS "void Carte::setDescription (std::string desc)"

.SS "void Carte::setName (std::string name)"

.SS "void Carte::setPlateau (int taille)"

.SS "int Carte::verif_taille (int taille)"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
