.TH "Carte" 3 "Thu Apr 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Carte
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCarte\fP (int taille)"
.br
.ti -1c
.RI "void \fBaffichage\fP ()"
.br
.ti -1c
.RI "void \fBsauvegarde\fP ()"
.br
.ti -1c
.RI "bool \fBcarte_existe\fP (string nom)"
.br
.ti -1c
.RI "void \fBchargement\fP (string nom_selection)"
.br
.ti -1c
.RI "int \fBquel_taille\fP (string nom)"
.br
.ti -1c
.RI "void \fBsuppression\fP (string nom)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
