.TH "Carte" 3 "Fri Apr 21 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Carte
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCarte\fP (int taille, std::string name, std::string description)"
.br
.ti -1c
.RI "void \fBaffichage\fP ()"
.br
.ti -1c
.RI "void \fBsauvegarde\fP ()"
.br
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.ti -1c
.RI "std::string \fBgetDescription\fP ()"
.br
.ti -1c
.RI "bool \fBcarte_existe\fP (std::string nom)"
.br
.ti -1c
.RI "void \fBchargement\fP (std::string nom_selection)"
.br
.ti -1c
.RI "int \fBquel_taille\fP (std::string nom)"
.br
.ti -1c
.RI "void \fBsuppression\fP (std::string nom)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
