.TH "competence" 3 "Fri Apr 21 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
competence
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBcompetence\fP (std::string skillName, int damage, int manaCost)"
.br
.ti -1c
.RI "\fBcompetence\fP (std::string skillName, int damage)"
.br
.ti -1c
.RI "std::string \fBgetSkillName\fP ()"
.br
.ti -1c
.RI "int \fBgetDamage\fP ()"
.br
.ti -1c
.RI "int \fBgetManaCost\fP ()"
.br
.ti -1c
.RI "template<typename T > std::string \fBtoString\fP (const T &valeur)"
.br
.ti -1c
.RI "void \fBprintCompetence\fP ()"
.br
.ti -1c
.RI "std::string \fBcompetenceString\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
