.TH "ent_combat" 3 "Fri Apr 21 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ent_combat
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fButil_comp\fP (\fBmonstre\fP *entite, \fBcompetence\fP *comp)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmonstre\fP * \fBentite\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
