.TH "entite" 3 "Sun Apr 23 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entite
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBmonstre\fP, and \fBpersonnage\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBentite\fP ()"
.br
.RI "Constructeur vide\&. "
.ti -1c
.RI "\fBentite\fP (std::string entiteId, std::string entiteName, int entiteHpMax, int entiteSpeed, int entiteManaMax, std::string entiteDescription, std::vector< \fBcompetence\fP > allSkills)"
.br
.RI "Constructeur avec tout\&. "
.ti -1c
.RI "template<typename T > std::string \fBtoString\fP (const T &valeur)"
.br
.ti -1c
.RI "std::string \fBgetID\fP ()"
.br
.RI "Getter pour l'id\&. "
.ti -1c
.RI "std::string \fBgetName\fP ()"
.br
.RI "Getter pour le nom\&. "
.ti -1c
.RI "std::string \fBgetDescription\fP ()"
.br
.RI "Getter pour la description\&. "
.ti -1c
.RI "int \fBgetHpMax\fP ()"
.br
.RI "Getter pour le nombre de points de vie max\&. "
.ti -1c
.RI "int \fBgetHpCurrent\fP ()"
.br
.RI "Getter pour le nombre de points de vie actuels\&. "
.ti -1c
.RI "int \fBgetSpeed\fP ()"
.br
.RI "Getter pour la vitesse d'attaque de l'entite\&. "
.ti -1c
.RI "bool \fBgetAlive\fP ()"
.br
.RI "Getter qui permet de savoir si l'entite est en vie\&. "
.ti -1c
.RI "int \fBgetManaMax\fP ()"
.br
.RI "Getter pour la mana maximum de l'entite\&. "
.ti -1c
.RI "int \fBgetManaCurrent\fP ()"
.br
.RI "Getter pour la mana actuelle de l'entite\&. "
.ti -1c
.RI "std::vector< \fBcompetence\fP > \fBgetSkillVect\fP ()"
.br
.RI "Getter qui renvoie un vecteur (std::vector) de compétences\&. "
.ti -1c
.RI "int \fBnbLigneFichier\fP (std::string nomFichier)"
.br
.RI "Retour d'une string représentant un entite\&. "
.ti -1c
.RI "std::string \fBentiteString\fP (std::string lettreEntite, std::string nomFichier)"
.br
.ti -1c
.RI "void \fBsaveInFile\fP (std::string lettreEntite, std::string nomFichier)"
.br
.RI "Permet d'écrire l'entite dans un fichier de sauvegarde\&. "
.ti -1c
.RI "void \fBprintEntite\fP ()"
.br
.RI "Pour tester\&. "
.ti -1c
.RI "bool \fBenleverVie\fP (int degats)"
.br
.RI "Enlève x points de vie a l'entite\&. "
.ti -1c
.RI "bool \fBenleverMana\fP (int skillManaCost)"
.br
.RI "Enlève x points de mana a l'entite\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "std::string \fBentiteId\fP"
.br
.ti -1c
.RI "std::string \fBentiteName\fP"
.br
.ti -1c
.RI "std::string \fBentiteDescription\fP"
.br
.ti -1c
.RI "int \fBentiteHpMax\fP"
.br
.ti -1c
.RI "int \fBentiteHpCurrent\fP"
.br
.ti -1c
.RI "int \fBentiteManaMax\fP"
.br
.ti -1c
.RI "int \fBentiteManaCurrent\fP"
.br
.ti -1c
.RI "int \fBentiteSpeed\fP"
.br
.ti -1c
.RI "bool \fBentiteAlive\fP"
.br
.ti -1c
.RI "std::vector< \fBcompetence\fP > \fBentiteSkillVect\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "entite::entite (std::string entiteId, std::string entiteName, int entiteHpMax, int entiteSpeed, int entiteManaMax, std::string entiteDescription, std::vector< \fBcompetence\fP > allSkills)"

.PP
Constructeur avec tout\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentiteId\fP L'identifiant de l'entite 
.br
\fIentiteName\fP Le nom de l'entite 
.br
\fIentiteHpMax\fP Les points de vie max de l'entite 
.br
\fIentiteSpeed\fP La vitesse de l'entite 
.br
\fIentiteManaMax\fP Les points de mana max de l'entite 
.br
\fIentiteDescription\fP La description de l'entite 
.br
\fIallSkills\fP Un vecteur (std::vector) contenant toutes les compétences de cette entite\&. 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "bool entite::enleverMana (int skillManaCost)"

.PP
Enlève x points de mana a l'entite\&. Cette fonction ne sert à rien, à part ne pas faire bugger les autres\&. 
.PP
\fBReturns:\fP
.RS 4
Un booléen vérifiant la capacité à dépenser la mana\&. 
.RE
.PP

.SS "bool entite::enleverVie (int degats)"

.PP
Enlève x points de vie a l'entite\&. Cette fonction permet d'enlever des points de vie\&. Elle permet aussi de savoir si une entite est en vie (ptsVie < 0) ou si elle est morte\&. 
.PP
\fBReturns:\fP
.RS 4
Un booléen qui est égal à \fCtrue\fP si le entite est mort, \fCfalse\fP sinon\&. 
.RE
.PP

.SS "int entite::nbLigneFichier (std::string nomFichier)"

.PP
Retour d'une string représentant un entite\&. Convertit un objet entite en une ligne de string\&. 
.PP
\fBPostcondition:\fP
.RS 4
La string contiendra les infos dans cet ordre :
.IP "\(bu" 2
entiteIdentifiant (type \fCm<entier>\fP)
.IP "\(bu" 2
nom de l'entite
.IP "\(bu" 2
nombre de points de vie
.IP "\(bu" 2
vitesse d'attaque
.IP "\(bu" 2
toutes les compétences , séparées par des \fC:\fPRetourne le nombre de lignes d'un fichier\&.
.PP
.RE
.PP
Compte le nb de lignes du fichier pour créer l'identifiant unique d'un entite\&. L'identifiant sera \fC nbLignes + 1 \fP 
.PP
\fBReturns:\fP
.RS 4
Un entier représentant le nombre de lignes\&. 
.RE
.PP
\fBParameters:\fP
.RS 4
\fInomFichier\fP Une string (std::string) qui sera le nom du fichier à ouvrir\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
