.TH "interface" 3 "Fri Apr 21 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
interface
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBcheckInput\fP (int x)"
.br
.ti -1c
.RI "\fBcompetence\fP \fBcreateCompetence\fP ()"
.br
.ti -1c
.RI "\fBcompetence\fP \fBcreateCompetenceMonstre\fP ()"
.br
.ti -1c
.RI "\fBmonstre\fP \fBcreateMonstre\fP ()"
.br
.ti -1c
.RI "std::vector< \fBcompetence\fP > \fBloadCompetenceFromFile\fP (std::string nomFichier, int numLigne)"
.br
.ti -1c
.RI "std::vector< \fBmonstre\fP > \fBloadAllMonstreFromFile\fP ()"
.br
.ti -1c
.RI "std::vector< \fBpersonnage\fP > \fBloadAllPersonnageFromFile\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
