.TH "jeu" 3 "Thu Apr 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
jeu \- Ceci sera la classe du jeu\&. Elle contient toutes les entités, la carte, ainsi que les fonctions nécessaires à la partie\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fonctionsjeu\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBjeu\fP ()"
.br
.RI "Constructeur par défaut sans argument\&. "
.ti -1c
.RI "\fB~jeu\fP ()"
.br
.RI "Destructeur par défaut\&. "
.ti -1c
.RI "void \fBdemarrer_jeu\fP ()"
.br
.RI "Fonction permettant de déterminer comment va démarrer la partie\&. "
.in -1c
.SH "Detailed Description"
.PP 
Ceci sera la classe du jeu\&. Elle contient toutes les entités, la carte, ainsi que les fonctions nécessaires à la partie\&. 

Cette classe contient les fonctions nécessaires au démarrage de la partie, au combat, ainsi que toutes les fonctions intermédiaires nécessaires au bon fonctionnement de celles-ci\&.
.PP
Librairies incluses :
.IP "\(bu" 2
std::stack ,
.IP "\(bu" 2
io ( depuis \fBio\&.h\fP ) 
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "jeu::jeu ()"

.PP
Constructeur par défaut sans argument\&. Avec ce constructeur, on peut créer toutes les entités du jeu\&.
.PP
.IP "\(bu" 2
Chargement de la carte,
.IP "\(bu" 2
Création d'un personnage,
.IP "\(bu" 2
Création de tous les monstres\&.
.PP
.PP
\fBSee also:\fP
.RS 4
perso(), carte(), \fBmonstre()\fP 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "void jeu::demarrer_jeu ()"

.PP
Fonction permettant de déterminer comment va démarrer la partie\&. Etant donné que cette fonction utilise des entités externes, il faut que tout le monde aie fini lesdites entités pour que la fonction compile\&.
.PP
\fBTodo\fP
.RS 4
demander à Loic et Ludivine de finir les entités (ou au moins nous dire la syntaxe demandée) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
