.TH "md___users_thibault__git_hub__c_e_r_i_software_engineering_game_1__r_e_a_d_m_e" 3 "Thu Apr 20 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md___users_thibault__git_hub__c_e_r_i_software_engineering_game_1__r_e_a_d_m_eThe Game 
 \- 
.SS "The Game, by les Poussins "
.PP
Bienvenue sur le Projet de Génie Logiciel L2S4 du CERI (2017)\&.
.PP
Les participants à ce projet sont :
.IP "\(bu" 2
Raphaël
.IP "\(bu" 2
Loïc
.IP "\(bu" 2
Malvina
.IP "\(bu" 2
Ludivine
.IP "\(bu" 2
Thibault
.PP
.PP
Le cahier des charges créé à la suite de la séance 1 est disponible sous le nom \fCCDC_v1\&.pdf\fP dans la racine du projet\&.
.PP
\fICe README sera mis à jour avec toutes les informations nécessaires au fur et à mesure de l'avancement du projet\&.\fP 
