.TH "monstre" 3 "Sun Apr 23 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
monstre
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBentite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBmonstre\fP ()"
.br
.RI "Constructeur vide\&. "
.ti -1c
.RI "\fBmonstre\fP (std::string entiteId, std::string entiteName, int entiteHpMax, int entiteSpeed, int entiteManaMax, std::string entiteDescription, std::vector< \fBcompetence\fP > allSkills)"
.br
.RI "Constructeur avec tout\&. "
.ti -1c
.RI "void \fBprintMonstre\fP ()"
.br
.RI "Pour tester\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "monstre::monstre (std::string entiteId, std::string entiteName, int entiteHpMax, int entiteSpeed, int entiteManaMax, std::string entiteDescription, std::vector< \fBcompetence\fP > allSkills)\fC [inline]\fP"

.PP
Constructeur avec tout\&. 
.PP
\fBParameters:\fP
.RS 4
\fIentiteId\fP L'identifiant du monstre 
.br
\fIentiteName\fP Le nom du monstre 
.br
\fIentiteHpMax\fP Les points de vie max du monstre 
.br
\fIentiteSpeed\fP La vitesse du monstre 
.br
\fIentiteManaMax\fP Les points de mana max du monstre 
.br
\fIentiteDescription\fP La entiteDescription du monstre 
.br
\fIallSkills\fP Un vecteur (std::vector) contenant toutes les compétences de ce monstre\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
