.TH "personnage" 3 "Fri Apr 21 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
personnage
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBmonstre\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpersonnage\fP (std::string name, int hpMax, int speed, int manaMax, std::string description)"
.br
.ti -1c
.RI "\fBpersonnage\fP (std::string name, int hpMax, int speed, int manaMax, std::string description, std::vector< \fBcompetence\fP > allSkills)"
.br
.ti -1c
.RI "int \fBgetManaMax\fP ()"
.br
.ti -1c
.RI "int \fBgetManaCurrent\fP ()"
.br
.ti -1c
.RI "std::string \fBgetDescription\fP ()"
.br
.ti -1c
.RI "std::string \fBpersonnageString\fP ()"
.br
.ti -1c
.RI "void \fBsavePersoInFile\fP ()"
.br
.ti -1c
.RI "bool \fBenleverMana\fP (int manaCost)"
.br
.ti -1c
.RI "void \fBprintPersonnage\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
