.TH "personnage" 3 "Wed Apr 26 2017" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
personnage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <personnage\&.h>\fP
.PP
Inherits \fBentite\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBpersonnage\fP ()"
.br
.RI "Constructeur vide\&. "
.ti -1c
.RI "\fBpersonnage\fP (std::string \fBentiteId\fP, std::string \fBentiteName\fP, int \fBentiteHpMax\fP, int \fBentiteSpeed\fP, int \fBentiteManaMax\fP, std::string \fBentiteDescription\fP, std::vector< \fBcompetence\fP > allSkills)"
.br
.ti -1c
.RI "void \fBprintPersonnage\fP ()"
.br
.RI "Fonction de test\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "personnage::personnage ()\fC [inline]\fP"

.PP
Constructeur vide\&. Le personnage créé aura 0 de mana, et n'aura aucune description\&. Mais il sera crée\&. 
.SS "personnage::personnage (std::string entiteId, std::string entiteName, int entiteHpMax, int entiteSpeed, int entiteManaMax, std::string entiteDescription, std::vector< \fBcompetence\fP > allSkills)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void personnage::printPersonnage ()"

.PP
Fonction de test\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
